name: ktty
description: "KTTY - Secure Mobile Terminal Relay"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  xterm: ^4.0.0
  web_socket_channel: ^3.0.3
  cryptography: ^2.9.0
  pqcrypto: ^0.1.0
  crypto: ^3.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ktty_logo.png
