name: ktty
description: "KTTY - Secure Mobile Terminal Relay"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  xterm: ^4.0.0
  web_socket_channel: ^3.0.3
  provider: ^6.0.0
  flutter_rust_bridge: ^2.12.0
  speech_to_text: ^7.0.0
  ktty_bridge:
    path: rust_builder

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ktty_logo.png
