/// Stub for flutter_rust_bridge generated code.
/// On native platforms, this would be replaced by the actual generated bridge.
class RustLib {
  static Future<void> init() async {
    // No-op on web; real implementation generated by flutter_rust_bridge for native.
  }
}
