const int kAppVersion = 7;
const String kAppBuildTime = String.fromEnvironment('BUILD_TIME', defaultValue: 'dev');

/// Encrypted relay URL for PWA. Generated by `ktty-agent --encrypt-url`.
/// Passed at build time: --dart-define=ENCRYPTED_RELAY_URL=<hex>
const String kEncryptedRelayUrl = String.fromEnvironment('ENCRYPTED_RELAY_URL', defaultValue: '');

const int kTerminalMaxLines = 1000;
const int kDefaultCols = 80;
const int kDefaultRows = 24;
const int kPortraitTerminalFlex = 62;
const int kPortraitKeyboardFlex = 38;
const Duration kPingInterval = Duration(seconds: 5);
const Duration kPingTimeout = Duration(seconds: 10);
const Duration kReconnectInitial = Duration(seconds: 1);
const Duration kReconnectMax = Duration(seconds: 30);
